# Generated by Django 3.2.9 on 2021-11-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211107_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='info_page',
            field=models.TextField(null=True),
        ),
    ]
